<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7VKRHC7" failures="1" tests="2" name="Footer Validations" time="74.691" errors="0" timestamp="2023-06-15T10:35:07 IST">
  <testcase classname="WebAutomation.tests.FailedLoginTest" name="returningCustomerSectionIsThere" time="3.157">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at WebAutomation.tests.FailedLoginTest.returningCustomerSectionIsThere(FailedLoginTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- returningCustomerSectionIsThere -->
  <testcase classname="WebAutomation.tests.FailedLoginTest" name="failedLogin" time="0.0">
    <skipped/>
  </testcase> <!-- failedLogin -->
</testsuite> <!-- Footer Validations -->
